//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSS_FAMERICANA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public long IdEmpleado { get; set; }
        public string TipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> IdHeader { get; set; }
    
        public virtual Header Header { get; set; }
    }
}
