//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSS_FAMERICANA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Header()
        {
            this.Detail = new HashSet<Detail>();
        }
    
        public int IdHeader { get; set; }
        public string Proceso { get; set; }
        public Nullable<int> RNC { get; set; }
        public Nullable<System.DateTime> PeriodoAutodeterminacion { get; set; }
        public Nullable<System.DateTime> FechaTransmision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Detail { get; set; }
    }
}
